appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LoYFYT6C9U3ctblO19hLx0p8OP4NcFMdWJFFmnQcX4wHR3Bgx7iI8FwiOMOetBr0IL2Sl+PBv+f9Q4ltTSGqWZRuZ/sSEPLonTrTUGnmz1slwPSTJzSSHfiyuyJiH+BKax4cOEXCvdIordQodnSbzOw7QRz4/Hv2d4f1mHZIezuEC3vIXqb4i097YNM+EqV/X/hyt9nR1oKj9ukF6mZxJooOSdjm+Tc0N6A9qtewfa8ccmZduDgp9T6/bYV57+5iGSNtJrixxDIps07ldFkITesz29tcErMBmDwE8KPzcg2ufTsD6HKO/XV3CFnv7u4QXDCsMf4JWV6VHAJMw9NxhkGlWmwjwPhETTJMtFJXFGMLEtWsQYKQc8Y9F8xJ5JRU87eydhxyzO1mvi3kFaoVp/Gk9BfLpanEPoLBQ6eSBNVP9QYcWOgazPqvkNoIB6KePRQUw7HLHyCVGIDgti/WFdtZMWU1bFZClGGe3urBZYiAonuOHxELX3MLthPj8PKV22Bm7ysG/oQ71dPt5UEAfMdsRLVs1vtV/ax8eFcRR8n+EJjMR/f8O/zSkGeYX6tA9qxDT1dmois8u4YV+alW6E0sygusJIdKyynEDpfRPGqqtqgwq0wWaZw9NzRtS2q7jhUiMaS3QBxq+WC1EQWvVHJUs1b60KhqvRxkGucgHqo=}
