travis:
  secure:
    BINSTAR_TOKEN: ouzqHXS5qOJEi5rLoNbXhkjcVWfwHJ0htZColaV5sGlEW4m1Zu3UgAB9dCqmyHLiGMiVzpQqdbM0t3Ozir9cvK7wuA9D5/kfRe+Yxt/I/1BYMldborwj/sVqbCBivW2jUUTaLkiPUqXDs4JokK8xaZo/oGTLnQzQA/q74QO3eI9GXzmSBu3m/EXz5cHjKBxwFMjqfiRoUa2lVtRhFgL40Y89iFfej+WDGS1Fapk9K+bLiyrIorSm+zON1rrExMMYpPY884fdOOAxxJYmySARfO+oVkduyRVNY8QtQZa2HR+/cGnsqnDjdEoAsDsMgtqZdX/2qu1Boq1DAt1GaTT8SyHJrD0/lbP4qn1mTYSO8XSbeSo2C7xvxMPD35oE5yO+T14dzQP9K0TtlMxmkKx9PJILMTOrfKPvirnusaz6auJ8VqyGOiaZBCbcuEfHKHEbrL5E+xmCWp1tpoihb2sGtk3ss5xB45mwPyFQQYe1JsjmK6cw5Etd2LroyVujzuBcWKpbPs4hNSw/LaQkTupuCi7EGbAKqUveA73vgqXVgKboP4NPU7Kj2hbMBOujeA0qHhU9YF9Ef/BOMvIc0fdZ6qKQ9UIlI+Jr7NjkhgC31OW9XnHOLMxQtPXSP4pY7dMU/J4FGv6uSUjPC3pT6yoJfeW9SDZMKZqqYMc3wmcfAkM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
